- name: Install Splunk Universal Forwarder
  hosts: all
  become: true

  vars:
    splunk_uf_rpm_url: "https://download.splunk.com/products/universalforwarder/releases/10.2.0/linux/splunkforwarder-10.2.0-d749cb17ea65.x86_64.rpm"
    splunk_pass: "StrongPassword123"

  tasks:

  - name: Create splunk group
    group:
      name: splunkfwd
      state: present

  - name: Create splunk user
    user:
      name: splunkfwd
      group: splunkfwd
      create_home: yes
      shell: /bin/bash
      state: present

  - name: Download UF RPM
    get_url:
      url: "{{ splunk_uf_rpm_url }}"
      dest: /tmp/splunkforwarder.rpm
    when: ansible_os_family == "RedHat"

  - name: Install Splunk forwarder RPM
    yum:
      name: /tmp/splunkforwarder.rpm
      state: present
      disable_gpg_check: yes
    when: ansible_os_family == "RedHat"

  # 🔥 CRITICAL FIX
  - name: Fix ownership of Splunk directory
    file:
      path: /opt/splunkforwarder
      owner: splunkfwd
      group: splunkfwd
      recurse: yes

  - name: Create user-seed.conf
    copy:
      dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
      content: |
        [user_info]
        USERNAME = admin
        PASSWORD = {{ splunk_pass }}
      owner: splunkfwd
      group: splunkfwd
      mode: '0600'

  # 🔥 RUN AS SPLUNK USER
  - name: Start Splunk Forwarder (first boot)
    command: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes
    become: true
    become_user: splunkfwd

  - name: Copy Splunk Cloud App
    copy:
      src: splunkclouduf.spl
      dest: /tmp/splunkclouduf.spl

  - name: Install Splunk Cloud UF App
    command: >
      /opt/splunkforwarder/bin/splunk install app /tmp/splunkclouduf.spl -auth admin:{{ splunk_pass }}
    become: true
    become_user: splunkfwd

  - name: Restart Splunk
    command: /opt/splunkforwarder/bin/splunk restart
    become: true
    become_user: splunkfwd